/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accounts with current balances
         * @description Returns every account (archived ones only when `includeArchived=true`), each with its current balance, plus the total across non-archived accounts. Accounts are few, so this list is not paginated.
         */
        get: operations["listAccounts"];
        put?: never;
        /**
         * Create an account
         * @description Creates an account. A non-zero `openingBalance` records an *opening* transaction dated `openingDate` through the ledger; a zero one records nothing. The opening balance is signed and may be negative (a card that already owes money).
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/balance-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily balances over a date range
         * @description One balance per calendar day from `from` to `to` inclusive, for each account and for the total. Element `i` of every `balances` array is the balance at the end of day `from + i`: the sum of the account's non-deleted entries dated on or before that day, the same value `getAccountBalanceAsOf` answers. `total` sums the non-archived accounts only, whether or not `includeArchived` is set. Read-only; derived from entries on every call, never stored.
         */
        get: operations["getBalanceHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit an account
         * @description Renames the account or changes its kind, opening balance or opening date. Opening balance and date edit the account's *opening* transaction through the ledger: zero to non-zero creates it, non-zero to zero deletes it, any other change rebalances it.
         */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/accounts/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive an account
         * @description Hides the account from pickers and dashboard totals. Its history stays readable and no transaction is altered. Reversible with `unarchiveAccount`.
         */
        post: operations["archiveAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unarchive an account
         * @description Restores the account to pickers and totals with its balance and history intact.
         */
        post: operations["unarchiveAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Balance of an account as of a date
         * @description The sum of the account's non-deleted entries dated on or before `asOf`. A date before the first transaction answers `"0"`. Correct on every read, cached values present or not.
         */
        get: operations["getAccountBalanceAsOf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description Returns every category (archived ones only when `includeArchived=true`). Not paginated.
         */
        get: operations["listCategories"];
        put?: never;
        /**
         * Create a category
         * @description Creates a category typed *expense* or *income*. The ledger-side backing it is created in the same atomic write and is never exposed here.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a category
         * @description Renames the category; renaming touches no transaction. May also change its type, but only while no transaction (soft-deleted included) references the category — once used, the type is immutable and a change is rejected with the structured error.
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/categories/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a category
         * @description Hides the category from pickers. History and reports keep showing it. Reversible.
         */
        post: operations["archiveCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unarchive a category
         * @description Restores the category to pickers with its history intact.
         */
        post: operations["unarchiveCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions
         * @description Lists transactions globally or filtered by account, kind, category, project and date range, ordered by `date` descending, ties broken by `id` descending (stable across pages). Paginated by `limit`/`offset`; the response carries the total match count. An offset past the last row returns an empty page with the correct total. A date range must start on or before its end and span at most 24 months.
         */
        get: operations["listTransactions"];
        put?: never;
        /**
         * Record a transaction
         * @description Records an expense, income or transfer (an *opening* transaction is created only through the account endpoints). The intent is translated into exactly two balanced ledger entries in one atomic write. Rejected with a structured error: non-positive amounts, future dates, archived or non-existent accounts/categories, category types that do not match the kind, transfers between the same account, projects on anything but an expense, closed projects.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Edit a transaction
         * @description Replaces the transaction with a complete new intent — kind included, so an expense may become an income or a transfer and back — validated exactly like a newly recorded one. All entries are regenerated in one atomic write. An *opening* transaction is not editable here (it stays *opening*, edited through the account form).
         */
        put: operations["updateTransaction"];
        post?: never;
        /**
         * Delete a transaction
         * @description Soft-deletes the transaction: it disappears from every list, balance and report, and the ledger still sums to zero. An *opening* transaction is deleted by setting its account's opening balance to zero, not here.
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduled-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List upcoming scheduled items
         * @description Returns every *active* scheduled item ordered by next due date ascending. Overdue items (due date passed, never confirmed) stay listed and flagged; items on an archived account stay listed and flagged. Completed items are gone. Not paginated.
         */
        get: operations["listScheduledItems"];
        put?: never;
        /**
         * Create a scheduled item
         * @description Creates a future bill or income. The next due date must be today or later on creation. A monthly recurrence anchored on the 29th–31st falls on the last day of shorter months. The category's type must match the kind (bill → expense category, income → income category).
         */
        post: operations["createScheduledItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduled-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Edit a scheduled item
         * @description Replaces the item's fields. Unlike creation, an edit may set the next due date in the past, which makes the item overdue. Transactions already recorded from this item are unaffected.
         */
        put: operations["updateScheduledItem"];
        post?: never;
        /**
         * Delete a scheduled item
         * @description Removes the item from the upcoming list and the projection. Transactions already recorded from it are unaffected.
         */
        delete: operations["deleteScheduledItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduled-items/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a scheduled occurrence as paid or received
         * @description Records a real transaction with the confirmed values (amount, date, account, category and description — pre-filled from the item in the UI, all changeable here) and, in the same atomic write, advances the item one period or completes it (*once* items, or items whose next due date would pass their end date). The confirmed values pass exactly the validation of a new transaction, so a confirmation on an archived account is rejected. The item's own amount and recurrence are never altered. The recorded transaction keeps no link to the item.
         */
        post: operations["confirmScheduledItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project the total balance to a horizon
         * @description Starts from the current total across non-archived accounts and applies every scheduled occurrence between today and `horizon` (at most 24 months ahead), expanded from the active items' recurrences. Occurrences already overdue come first, marked, one per missed period for recurring items. The response is a running series; the UI flags any occurrence whose running balance is negative.
         */
        get: operations["getProjection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects with spend figures
         * @description Every project (closed ones included), each with total spent, remaining budget and over-budget flag when a budget exists. Not paginated.
         */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an unused project
         * @description Deletes the project only if no transaction references it; otherwise answers `422 DOMAIN_RULE_VIOLATION` telling the user to close it instead.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /**
         * Edit a project
         * @description Renames the project or sets/changes/removes its budget (a `null` budget removes it).
         */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close a project
         * @description Stops the project being offered on new transactions and edits. Its report stays readable. Reversible with `reopenProject`.
         */
        post: operations["closeProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen a closed project */
        post: operations["reopenProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a project's expenses
         * @description The expenses tagged with this project, ordered and paginated like `listTransactions`.
         */
        get: operations["listProjectTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly expenses by category
         * @description For one calendar month: total spent per expense category (only categories with activity), the grand total, and the transactions behind each category. Income and transfers never appear. A month with no expenses answers an empty category list and a `"0"` total.
         */
        get: operations["getMonthlyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Group similar transactions in a date range
         * @description Deterministic, locally computed grouping by normalised description (lower-cased, whitespace-collapsed, one trailing digit run stripped; a description that normalises to nothing groups by its trimmed original). Groups are ordered by total descending. Also returns the five most expensive individual transactions of the period and the most expensive group's key. The range must start on or before its end and span at most 24 months. An empty period answers an empty report.
         */
        get: operations["getSimilarReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/similar/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI narrative over the similar-transaction report, streamed
         * @description Sends the same grouped data to the configured LLM provider, with each description stripped of Markdown and HTML marks and line breaks, and streams back a short prose summary in Markdown (one or two paragraphs, the most expensive group in bold) as Server-Sent Events. Requires `LLM_API_KEY`; without it the answer is `422 AI_NOT_CONFIGURED`. The provider is called once and never retried.
         *
         *     **Before any text** the status line is not yet sent, so failures keep their JSON error responses: a provider rate limit `503 AI_RATE_LIMITED`, any other provider failure or an answer with no text `502 AI_PROVIDER_ERROR`, and no text within `LLM_TIMEOUT_MS` `504 AI_TIMEOUT`, counted from the provider call. Text means at least one non-whitespace character.
         *
         *     **Once text flows** the answer is `200 text/event-stream`. Each event has one JSON `data` line. `event: delta` carries a `NarrativeDeltaEvent`, in the order the provider produced them; concatenating every `text` gives the narrative. `event: end` carries a `NarrativeEndEvent` and is always the last event. A failure after the first delta, a gap longer than `LLM_TIMEOUT_MS` between deltas, or reaching the output cap ends the stream with `outcome: incomplete` and a `reason`. There is no overall time limit. A body that closes without an `end` event means the connection was lost; clients treat it as incomplete.
         *
         *     Closing the connection ends the provider request. The deterministic report is never affected.
         */
        post: operations["generateSimilarNarrative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether the AI narrative is available
         * @description `configured` is true when the server has an LLM API key. It never returns the key, and it never calls the provider, so `true` does not promise that the provider will answer. The narrative endpoint still returns `AI_NOT_CONFIGURED` and the other AI errors as before.
         */
        get: operations["getAiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Entity id, a BIGINT serialized as a decimal string.
         * @example 42
         */
        Id: string;
        /**
         * @description Integer cents as a decimal string; never a JSON number. The ±10^15-cent guard is validated after bigint conversion, not by this pattern.
         * @example 4250
         */
        Money: string;
        /**
         * Format: date
         * @description Calendar date, `YYYY-MM-DD`, no time component.
         * @example 2026-09-10
         */
        DateOnly: string;
        /**
         * @description The user-facing kind of an account.
         * @example bank
         * @enum {string}
         */
        AccountKind: "bank" | "cash" | "card";
        /**
         * @description Whether the category classifies expenses or income.
         * @example expense
         * @enum {string}
         */
        CategoryType: "expense" | "income";
        /**
         * @description The intent a transaction expresses. `opening` appears only in responses; it is created and edited through the account endpoints.
         * @example expense
         * @enum {string}
         */
        TransactionKind: "expense" | "income" | "transfer" | "opening";
        /**
         * @description A future payment (bill) or a future receipt (income).
         * @example bill
         * @enum {string}
         */
        ScheduledItemKind: "bill" | "income";
        /**
         * @description Monthly anchored on the 29th–31st clamps to the last day of shorter months.
         * @example monthly
         * @enum {string}
         */
        Recurrence: "once" | "weekly" | "monthly";
        /**
         * @example active
         * @enum {string}
         */
        ScheduledItemStatus: "active" | "completed";
        /**
         * @example active
         * @enum {string}
         */
        ProjectStatus: "active" | "closed";
        /**
         * @description Every error code the API can answer with. One code per failure class.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_FAILED" | "NOT_FOUND" | "DUPLICATE_NAME" | "DOMAIN_RULE_VIOLATION" | "AI_NOT_CONFIGURED" | "AI_PROVIDER_ERROR" | "AI_RATE_LIMITED" | "AI_TIMEOUT" | "INTERNAL_ERROR";
        ErrorDetail: {
            /**
             * @description The offending request field, dot-separated for nesting.
             * @example amount
             */
            field: string;
            /**
             * @description What is wrong with it.
             * @example amount must be a positive integer number of cents
             */
            message: string;
        };
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            /**
             * @description Human-readable summary, safe to show the user.
             * @example Validation failed
             */
            message: string;
            /** @description Field-level details when a field is nameable; absent otherwise. */
            details?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uuid
             * @description Matches the `X-Correlation-Id` header and exactly one stdout log line.
             * @example 6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10
             */
            correlationId: string;
        };
        AccountCreateRequest: {
            /**
             * @description 1–60 characters after trimming; unique among accounts, archived included.
             * @example Checking
             */
            name: string;
            kind: components["schemas"]["AccountKind"];
            /**
             * @description Signed cents; may be negative (existing debt) or `"0"` (no opening transaction).
             * @example 150000
             */
            openingBalance: components["schemas"]["Money"];
            /**
             * @description The opening transaction's date; not in the future.
             * @example 2026-09-01
             */
            openingDate: components["schemas"]["DateOnly"];
        };
        AccountUpdateRequest: {
            /** @example Everyday Checking */
            name?: string;
            kind?: components["schemas"]["AccountKind"];
            /**
             * @description New signed opening balance; `"0"` deletes the opening transaction.
             * @example 175000
             */
            openingBalance?: components["schemas"]["Money"];
            openingDate?: components["schemas"]["DateOnly"];
        };
        AccountResponse: {
            id: components["schemas"]["Id"];
            /** @example Checking */
            name: string;
            kind: components["schemas"]["AccountKind"];
            /**
             * @description Signed cents of the opening transaction; `"0"` when there is none.
             * @example 150000
             */
            openingBalance: components["schemas"]["Money"];
            openingDate: components["schemas"]["DateOnly"];
            /** @example false */
            archived: boolean;
            /**
             * @description Current balance, signed cents.
             * @example 445750
             */
            balance: components["schemas"]["Money"];
        };
        AccountListResponse: {
            items: components["schemas"]["AccountResponse"][];
            /**
             * @description Sum of current balances across non-archived accounts, signed cents.
             * @example 395750
             */
            totalBalance: components["schemas"]["Money"];
        };
        BalanceResponse: {
            accountId: components["schemas"]["Id"];
            asOf: components["schemas"]["DateOnly"];
            /**
             * @description Sum of the account's non-deleted entries dated on or before `asOf`.
             * @example 145750
             */
            balance: components["schemas"]["Money"];
        };
        AccountBalanceSeries: {
            accountId: components["schemas"]["Id"];
            /** @example false */
            archived: boolean;
            /**
             * @description One signed-cents balance per day, `from` first.
             * @example [
             *       "445750",
             *       "441500",
             *       "441500"
             *     ]
             */
            balances: components["schemas"]["Money"][];
        };
        BalanceHistoryResponse: {
            from: components["schemas"]["DateOnly"];
            to: components["schemas"]["DateOnly"];
            /**
             * @description Per day, the sum of the non-archived accounts' balances, signed cents. Its last element equals `AccountListResponse.totalBalance` when `to` is today.
             * @example [
             *       "395750",
             *       "391500",
             *       "391500"
             *     ]
             */
            total: components["schemas"]["Money"][];
            /** @description Same accounts and order as `listAccounts` with the same `includeArchived`. */
            accounts: components["schemas"]["AccountBalanceSeries"][];
        };
        CategoryCreateRequest: {
            /**
             * @description 1–60 characters after trimming; unique among categories, archived included.
             * @example Pets
             */
            name: string;
            type: components["schemas"]["CategoryType"];
        };
        CategoryUpdateRequest: {
            /** @example Pets & Vet */
            name: string;
            /** @description Optional. Accepted only while no transaction (soft-deleted included) references the category; on a used category a type change is rejected with the structured error. Omitted means the type is unchanged. */
            type?: components["schemas"]["CategoryType"];
        };
        CategoryResponse: {
            id: components["schemas"]["Id"];
            /** @example Groceries */
            name: string;
            type: components["schemas"]["CategoryType"];
            /** @example false */
            archived: boolean;
        };
        ExpenseIntent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "expense";
            /** @description Not in the future. */
            date: components["schemas"]["DateOnly"];
            /**
             * @description 1–120 characters after trimming; whitespace-only is rejected.
             * @example Market
             */
            description: string;
            /**
             * @description Positive cents.
             * @example 4250
             */
            amount: components["schemas"]["Money"];
            /** @description The non-archived account the money leaves. */
            accountId: components["schemas"]["Id"];
            /** @description A non-archived category of type `expense`. */
            categoryId: components["schemas"]["Id"];
            /** @description Optional; an active project. Only expenses may carry one. */
            projectId?: components["schemas"]["Id"];
        };
        IncomeIntent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "income";
            /** @description Not in the future. */
            date: components["schemas"]["DateOnly"];
            /** @example September salary */
            description: string;
            /**
             * @description Positive cents.
             * @example 300000
             */
            amount: components["schemas"]["Money"];
            /** @description The non-archived account the money enters. */
            accountId: components["schemas"]["Id"];
            /** @description A non-archived category of type `income`. */
            categoryId: components["schemas"]["Id"];
        };
        TransferIntent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "transfer";
            /** @description Not in the future. */
            date: components["schemas"]["DateOnly"];
            /** @example To savings */
            description: string;
            /**
             * @description Positive cents.
             * @example 50000
             */
            amount: components["schemas"]["Money"];
            /** @description Source account, non-archived. */
            accountId: components["schemas"]["Id"];
            /** @description Destination account, non-archived, different from `accountId`. Transfers carry no category and no project. */
            counterAccountId: components["schemas"]["Id"];
        };
        /** @description A complete intent, discriminated by `kind`. Used for recording and for editing (an edit replaces the whole intent, kind included). */
        TransactionRequest: components["schemas"]["ExpenseIntent"] | components["schemas"]["IncomeIntent"] | components["schemas"]["TransferIntent"];
        TransactionResponse: {
            id: components["schemas"]["Id"];
            kind: components["schemas"]["TransactionKind"];
            date: components["schemas"]["DateOnly"];
            /** @example Market */
            description: string;
            /**
             * @description Positive cents for expense, income and transfer; signed cents for `opening`.
             * @example 4250
             */
            amount: components["schemas"]["Money"];
            /** @description The account (transfer — the source). */
            accountId: components["schemas"]["Id"];
            /** @description Transfer destination; absent on other kinds. */
            counterAccountId?: components["schemas"]["Id"];
            /** @description Present on expense and income; absent on transfer and opening. */
            categoryId?: components["schemas"]["Id"];
            /** @description Present when the expense is tagged with a project. */
            projectId?: components["schemas"]["Id"];
        };
        /** @description The shared paginated shape — `items`, `total`, `limit`, `offset`. */
        PaginatedTransactions: {
            items: components["schemas"]["TransactionResponse"][];
            /**
             * @description Total matching transactions across all pages.
             * @example 87
             */
            total: number;
            /** @example 50 */
            limit: number;
            /** @example 0 */
            offset: number;
        };
        ScheduledItemRequest: {
            kind: components["schemas"]["ScheduledItemKind"];
            /** @example Rent */
            description: string;
            /**
             * @description Positive cents; what is expected, not what will necessarily be paid.
             * @example 120000
             */
            amount: components["schemas"]["Money"];
            /** @description The non-archived account the money will leave or enter. */
            accountId: components["schemas"]["Id"];
            /** @description Type must match `kind` (bill → expense, income → income). */
            categoryId: components["schemas"]["Id"];
            /**
             * @description Today or later on creation; an edit may set the past (item becomes overdue).
             * @example 2026-10-01
             */
            nextDueDate: components["schemas"]["DateOnly"];
            recurrence: components["schemas"]["Recurrence"];
            /** @description Optional; not before `nextDueDate`. No occurrence after it counts. */
            endDate?: components["schemas"]["DateOnly"];
        };
        ScheduledItemResponse: {
            id: components["schemas"]["Id"];
            kind: components["schemas"]["ScheduledItemKind"];
            /** @example Rent */
            description: string;
            /** @example 120000 */
            amount: components["schemas"]["Money"];
            accountId: components["schemas"]["Id"];
            categoryId: components["schemas"]["Id"];
            nextDueDate: components["schemas"]["DateOnly"];
            recurrence: components["schemas"]["Recurrence"];
            endDate?: components["schemas"]["DateOnly"];
            status: components["schemas"]["ScheduledItemStatus"];
            /**
             * @description The next due date has passed without a confirmation.
             * @example false
             */
            overdue: boolean;
            /**
             * @description Missed periods since the next due date; `0` when not overdue.
             * @example 0
             */
            overdueCount: number;
            /**
             * @description The item's account is archived; the item stays listed, flagged, and a confirmation on it is rejected.
             * @example false
             */
            accountArchived: boolean;
        };
        /** @description The confirmed values; the UI pre-fills them from the item, all are changeable and all pass exactly the validation of a new transaction. */
        ConfirmScheduledItemRequest: {
            /**
             * @description Positive cents actually paid or received.
             * @example 125000
             */
            amount: components["schemas"]["Money"];
            /**
             * @description The real transaction's date; not in the future.
             * @example 2026-10-03
             */
            date: components["schemas"]["DateOnly"];
            accountId: components["schemas"]["Id"];
            categoryId: components["schemas"]["Id"];
            /** @example Rent */
            description: string;
        };
        ConfirmScheduledItemResponse: {
            /** @description The recorded expense or income. */
            transaction: components["schemas"]["TransactionResponse"];
            /** @description The item after advancing or completing; `status` says which. */
            item: components["schemas"]["ScheduledItemResponse"];
        };
        ProjectionOccurrence: {
            /**
             * @description The occurrence's due date (for an overdue one, the missed date).
             * @example 2026-10-01
             */
            date: components["schemas"]["DateOnly"];
            scheduledItemId: components["schemas"]["Id"];
            /** @example Rent */
            description: string;
            kind: components["schemas"]["ScheduledItemKind"];
            /**
             * @description Positive cents; bills subtract, income adds.
             * @example 120000
             */
            amount: components["schemas"]["Money"];
            /**
             * @description Projected total after this occurrence, signed cents. Negative means shortfall.
             * @example 325750
             */
            runningBalance: components["schemas"]["Money"];
            /**
             * @description This occurrence was due before today and is placed at the start of the series.
             * @example false
             */
            overdue: boolean;
        };
        ProjectionResponse: {
            horizon: components["schemas"]["DateOnly"];
            /**
             * @description Current total across non-archived accounts, signed cents.
             * @example 445750
             */
            startingBalance: components["schemas"]["Money"];
            /**
             * @description Running balance after the last occurrence.
             * @example 545750
             */
            finalBalance: components["schemas"]["Money"];
            /** @description Overdue occurrences first, then chronological up to the horizon. */
            occurrences: components["schemas"]["ProjectionOccurrence"][];
        };
        ProjectCreateRequest: {
            /**
             * @description 1–60 characters after trimming; unique among projects, closed included.
             * @example Trip to France
             */
            name: string;
            /**
             * @description Optional positive cents. Absent means no budget (distinct from zero).
             * @example 500000
             */
            budget?: components["schemas"]["Money"];
        };
        ProjectUpdateRequest: {
            /** @example Trip to France 2027 */
            name?: string;
            /**
             * @description New positive budget in cents, or `null` to remove the budget.
             * @example 600000
             */
            budget?: components["schemas"]["Money"] | null;
        };
        ProjectResponse: {
            id: components["schemas"]["Id"];
            /** @example Trip to France */
            name: string;
            status: components["schemas"]["ProjectStatus"];
            /**
             * @description Absent when the project has no budget.
             * @example 500000
             */
            budget?: components["schemas"]["Money"];
            /**
             * @description Sum of the project's non-deleted expenses, in cents.
             * @example 110000
             */
            spent: components["schemas"]["Money"];
            /**
             * @description `budget − spent`, signed; absent when there is no budget.
             * @example 390000
             */
            remaining?: components["schemas"]["Money"];
            /**
             * @description `spent > budget`; always `false` without a budget.
             * @example false
             */
            overBudget: boolean;
        };
        MonthlyReportCategory: {
            categoryId: components["schemas"]["Id"];
            /** @example Groceries */
            categoryName: string;
            /**
             * @description The month's expenses in this category, positive cents.
             * @example 7250
             */
            total: components["schemas"]["Money"];
            /** @description The expenses behind the total, date descending. */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        MonthlyReportResponse: {
            /** @example 2026-09 */
            month: string;
            /**
             * @description Sum of every category total; `"0"` for a month with no expenses.
             * @example 19250
             */
            grandTotal: components["schemas"]["Money"];
            /** @description Only categories with activity, ordered by total descending. */
            categories: components["schemas"]["MonthlyReportCategory"][];
        };
        SimilarGroup: {
            /**
             * @description The normalised description (or the trimmed original when normalisation empties it).
             * @example uber
             */
            key: string;
            /** @example 3 */
            count: number;
            /**
             * @description Sum of the group's amounts, positive cents.
             * @example 8700
             */
            total: components["schemas"]["Money"];
            /** @description The group's members, date descending. */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        SimilarReportResponse: {
            from: components["schemas"]["DateOnly"];
            to: components["schemas"]["DateOnly"];
            /** @description Ordered by total descending. Empty for a period without transactions. */
            groups: components["schemas"]["SimilarGroup"][];
            /** @description The five most expensive individual transactions of the period. */
            topTransactions: components["schemas"]["TransactionResponse"][];
            /**
             * @description `key` of the most expensive group; `null` for an empty report.
             * @example uber
             */
            topGroupKey: string | null;
        };
        NarrativeRequest: {
            /**
             * @description Same bounds as the similar report (start ≤ end, at most 24 months).
             * @example 2026-09-01
             */
            from: components["schemas"]["DateOnly"];
            /** @example 2026-09-30 */
            to: components["schemas"]["DateOnly"];
        };
        /** @description `data` of an `event: delta`. The next piece of the narrative, in order. */
        NarrativeDeltaEvent: {
            /**
             * @description Markdown text to append to what arrived before.
             * @example - **Rent
             */
            text: string;
        };
        /** @description `data` of the `event: end` that closes every stream. `reason` is present exactly when `outcome` is `incomplete`. */
        NarrativeEndEvent: {
            /**
             * @example complete
             * @enum {string}
             */
            outcome: "complete" | "incomplete";
            /**
             * @description `provider_error`: the provider failed or stopped for any reason other than finishing or the cap. `timeout`: no text for `LLM_TIMEOUT_MS`. `length`: the output cap was reached.
             * @example timeout
             * @enum {string}
             */
            reason?: "provider_error" | "timeout" | "length";
        };
        AiStatusResponse: {
            /**
             * @description True when an LLM API key is set on the server.
             * @example true
             */
            configured: boolean;
        };
    };
    responses: {
        /** @description The request's shape, a field's format, the money guard, a date rule or a pagination bound failed (`VALIDATION_FAILED`). */
        ValidationError: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION_FAILED",
                 *       "message": "Validation failed",
                 *       "details": [
                 *         {
                 *           "field": "amount",
                 *           "message": "amount must be a string of integer cents with absolute value at most 10^15"
                 *         }
                 *       ],
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The id in the URL path does not exist or is deleted (`NOT_FOUND`). */
        NotFound: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Transaction 42 does not exist",
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Another account, category or project (archived and closed rows included) already holds this name, compared case- and whitespace-insensitively (`DUPLICATE_NAME`). */
        DuplicateName: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "DUPLICATE_NAME",
                 *       "message": "An account named \"Checking\" already exists",
                 *       "details": [
                 *         {
                 *           "field": "name",
                 *           "message": "name is already in use"
                 *         }
                 *       ],
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A domain rule rejected the request (`DOMAIN_RULE_VIOLATION`): archived account or category, category type mismatch, transfer between the same account, closed or non-existent referenced entity, project on a non-expense, delete of a used project, end date before due date, and similar. */
        DomainRuleViolation: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "DOMAIN_RULE_VIOLATION",
                 *       "message": "A transfer cannot use the same account as source and destination",
                 *       "details": [
                 *         {
                 *           "field": "counterAccountId",
                 *           "message": "must differ from accountId"
                 *         }
                 *       ],
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `LLM_API_KEY` is empty: the AI narrative is not configured (`AI_NOT_CONFIGURED`). */
        AiNotConfigured: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "AI_NOT_CONFIGURED",
                 *       "message": "No LLM provider key is configured",
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The LLM provider returned an error (`AI_PROVIDER_ERROR`). Not retried. */
        AiProviderError: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "AI_PROVIDER_ERROR",
                 *       "message": "The LLM provider answered with an error",
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The LLM provider rate-limited the call (`AI_RATE_LIMITED`). Not retried. */
        AiRateLimited: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "AI_RATE_LIMITED",
                 *       "message": "The LLM provider rate limit was hit",
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The LLM provider did not answer within `LLM_TIMEOUT_MS` (`AI_TIMEOUT`). Not retried. */
        AiTimeout: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "AI_TIMEOUT",
                 *       "message": "The LLM provider timed out after 10000 ms",
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unhandled error (`INTERNAL_ERROR`); logged with stack trace under the same correlation id. */
        InternalError: {
            headers: {
                "X-Correlation-Id": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INTERNAL_ERROR",
                 *       "message": "Something went wrong",
                 *       "correlationId": "6f1b0c1e-8a24-4a5f-9b6d-2f3a7c1d9e10"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description The entity's id. */
        IdParam: components["schemas"]["Id"];
        /** @description Page size, 1–200. Above 200 is rejected with `VALIDATION_FAILED`. */
        LimitParam: number;
        /** @description Rows to skip. An offset past the last row returns an empty page with the correct total. */
        OffsetParam: number;
        /**
         * @description Range start, inclusive. With `to`, must not start after it nor span more than 24 months.
         * @example 2026-09-01
         */
        FromParam: string;
        /**
         * @description Range end, inclusive.
         * @example 2026-09-30
         */
        ToParam: string;
        /**
         * @description Only transactions whose description contains this text, ignoring case. Matched literally: `%`, `_` and `\` are not wildcards. Trimmed; 1–60 characters after trimming, otherwise `VALIDATION_FAILED`. Combined with the other filters by AND. Order and pagination are unchanged.
         * @example uber
         */
        QueryParam: string;
        /**
         * @description Range start, inclusive. Must not start after `to` nor span more than 24 months.
         * @example 2026-09-01
         */
        FromRequiredParam: string;
        /**
         * @description Range end, inclusive.
         * @example 2026-09-30
         */
        ToRequiredParam: string;
    };
    requestBodies: never;
    headers: {
        /** @description The request's correlation id; matches the `correlationId` in the body and the stdout log line. */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAccounts: {
        parameters: {
            query?: {
                /** @description Include archived accounts in the list. Defaults to false. */
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts and the non-archived total. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateRequest"];
            };
        };
        responses: {
            /** @description The created account, balance included. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["DuplicateName"];
            500: components["responses"]["InternalError"];
        };
    };
    getBalanceHistory: {
        parameters: {
            query?: {
                /**
                 * @description First day, inclusive. When absent, the earliest entry date of the non-archived accounts, whether or not `includeArchived` is set, clamped to 10 years before `to`; `to` itself when they have no entries. Must not be after `to`, and the span must not exceed 10 years.
                 * @example 2026-08-24
                 */
                from?: string;
                /**
                 * @description Last day, inclusive. Defaults to today in `APP_TIMEZONE`. Must not be after today, otherwise `VALIDATION_FAILED`.
                 * @example 2026-09-22
                 */
                to?: string;
                /** @description Also return archived accounts' series. They never count toward `total`. */
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The daily series. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceHistoryResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdateRequest"];
            };
        };
        responses: {
            /** @description The updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["DuplicateName"];
            422: components["responses"]["DomainRuleViolation"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    unarchiveAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The unarchived account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getAccountBalanceAsOf: {
        parameters: {
            query: {
                /**
                 * @description The date to compute the balance at, inclusive.
                 * @example 2026-09-12
                 */
                asOf: string;
            };
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The balance at that date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                /** @description Include archived categories. Defaults to false. */
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The categories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateRequest"];
            };
        };
        responses: {
            /** @description The created category. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["DuplicateName"];
            500: components["responses"]["InternalError"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description The renamed category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["DuplicateName"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    unarchiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The unarchived category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                /** @description Only transactions touching this account. */
                accountId?: components["schemas"]["Id"];
                /** @description Only this kind. */
                kind?: components["schemas"]["TransactionKind"];
                /** @description Only this category. */
                categoryId?: components["schemas"]["Id"];
                /** @description Only this project. */
                projectId?: components["schemas"]["Id"];
                /**
                 * @description Range start, inclusive. With `to`, must not start after it nor span more than 24 months.
                 * @example 2026-09-01
                 */
                from?: components["parameters"]["FromParam"];
                /**
                 * @description Range end, inclusive.
                 * @example 2026-09-30
                 */
                to?: components["parameters"]["ToParam"];
                /**
                 * @description Only transactions whose description contains this text, ignoring case. Matched literally: `%`, `_` and `\` are not wildcards. Trimmed; 1–60 characters after trimming, otherwise `VALIDATION_FAILED`. Combined with the other filters by AND. Order and pagination are unchanged.
                 * @example uber
                 */
                q?: components["parameters"]["QueryParam"];
                /** @description Page size, 1–200. Above 200 is rejected with `VALIDATION_FAILED`. */
                limit?: components["parameters"]["LimitParam"];
                /** @description Rows to skip. An offset past the last row returns an empty page with the correct total. */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of transactions plus the total match count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTransactions"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description The recorded transaction. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            422: components["responses"]["DomainRuleViolation"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description The updated transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["DomainRuleViolation"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted; no content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["DomainRuleViolation"];
            500: components["responses"]["InternalError"];
        };
    };
    listScheduledItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active scheduled items, soonest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledItemResponse"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createScheduledItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledItemRequest"];
            };
        };
        responses: {
            /** @description The created item. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledItemResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            422: components["responses"]["DomainRuleViolation"];
            500: components["responses"]["InternalError"];
        };
    };
    updateScheduledItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledItemRequest"];
            };
        };
        responses: {
            /** @description The updated item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledItemResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["DomainRuleViolation"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteScheduledItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted; no content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    confirmScheduledItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmScheduledItemRequest"];
            };
        };
        responses: {
            /** @description The recorded transaction and the item's new state. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmScheduledItemResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["DomainRuleViolation"];
            500: components["responses"]["InternalError"];
        };
    };
    getProjection: {
        parameters: {
            query: {
                /**
                 * @description Last date included, at most 24 months after today.
                 * @example 2026-11-30
                 */
                horizon: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The projected series and final balance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description The created project. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["DuplicateName"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted; no content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["DomainRuleViolation"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description The updated project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["DuplicateName"];
            500: components["responses"]["InternalError"];
        };
    };
    closeProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The closed project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reopenProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reopened project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listProjectTransactions: {
        parameters: {
            query?: {
                /** @description Page size, 1–200. Above 200 is rejected with `VALIDATION_FAILED`. */
                limit?: components["parameters"]["LimitParam"];
                /** @description Rows to skip. An offset past the last row returns an empty page with the correct total. */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path: {
                /** @description The entity's id. */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the project's expenses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTransactions"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getMonthlyReport: {
        parameters: {
            query: {
                /**
                 * @description The calendar month, `YYYY-MM`.
                 * @example 2026-09
                 */
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The month's report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    getSimilarReport: {
        parameters: {
            query: {
                /**
                 * @description Range start, inclusive. Must not start after `to` nor span more than 24 months.
                 * @example 2026-09-01
                 */
                from: components["parameters"]["FromRequiredParam"];
                /**
                 * @description Range end, inclusive.
                 * @example 2026-09-30
                 */
                to: components["parameters"]["ToRequiredParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The grouped report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarReportResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    generateSimilarNarrative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NarrativeRequest"];
            };
        };
        responses: {
            /** @description The narrative as Server-Sent Events: zero or more `delta` events, then one `end` event. See `NarrativeDeltaEvent` and `NarrativeEndEvent`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example event: delta
                     *     data: {"text":"You spent $412.30 in September.\n\n- **Rent"}
                     *
                     *     event: delta
                     *     data: {"text":": $300.00 (1)**\n- Uber: $87.00 (3)\n"}
                     *
                     *     event: end
                     *     data: {"outcome":"complete"}
                     */
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["ValidationError"];
            422: components["responses"]["AiNotConfigured"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["AiProviderError"];
            503: components["responses"]["AiRateLimited"];
            504: components["responses"]["AiTimeout"];
        };
    };
    getAiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiStatusResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
